### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by raghupviyer** [mitchwadair/vanilla-spa-router#2]
When I got to url/about it says page not found, i downloaded the zip of this project ran it with the live server extension
It works fine if i navigate to the about or any other page via the button clicks but if i go directly to the url eg /about ... Then it gives an error, says page not found

In the video it works somehow. ... I don't know ... Please help

**Comment by mitchwadair** [comment]
make sure live server extension is serving the root `index.html` for unknown paths.  The [`handleLocation`](https://github.com/mitchwadair/vanilla-spa-router/blob/db49c35828f45b47abdcad5f0de79444b3f24d0b/js/router.js#L15) function needs to be run, which is from `index.html`.

In your VSCode settings, add:
```json
"liveServer.settings.file": "index.html"
```

**Comment by raghupviyer** [comment]
Thanks ... that's amazing ... it worked
 

but now my only  question is ... how to host this webpage on some place  ... what setting would i have to do there... currently on netlify unable to figure it out

the same prblem occurs when hosted on netlify but works perfectly on liveserver locally

**Comment by Fake-User** [comment]
I had the same question, & came across [Netlify Redirects Configuration](https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file)
Ill play with it tonight & see if I can get it working

**Comment by Fake-User** [comment]
I found this [article](https://www.netlify.com/blog/2020/04/07/creating-better-more-predictable-redirect-rules-for-spas/)
& created an _redirect file in my projects root directory with the single rule:
/*   /index.html   200
works fine

one thing to note,
the Netlify redirect rules can take a few minuets to update after a deploy
so just wait a bit before you test it

**Comment by raghupviyer** [comment]
awesome ... Thanks a lot for the help
